apiVersion: v1
data:
  quarkus.datasource.jdbc.url: jdbc:postgresql://bad-db:5432/villains_database
  quarkus.hibernate-orm.database.generation: validate
  quarkus.hibernate-orm.sql-load-script: no-file
  quarkus.otel.exporter.otlp.traces.endpoint: http://otel-collector:4317
kind: ConfigMap
metadata:
  labels:
    app: rest-villains
    app.kubernetes.io/instance: quarkus-super-heroes
    application: villains-service
    system: quarkus-super-heroes
  name: rest-villains-config